//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimaLuvApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimaLuvDataEntities : DbContext
    {
        public AnimaLuvDataEntities()
            : base("name=AnimaLuvDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<CustomOrder> CustomOrders { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Stuffing> Stuffings { get; set; }
    }
}
