//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimaLuvApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrder
    {
        public int CustomOrderID { get; set; }
        public string Name { get; set; }
        public int AnimalID { get; set; }
        public int SizeID { get; set; }
        public int ColorID { get; set; }
        public int MaterialID { get; set; }
        public int StuffingID { get; set; }
        public int OutfitID { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Color Color { get; set; }
        public virtual Material Material { get; set; }
        public virtual Outfit Outfit { get; set; }
        public virtual Size Size { get; set; }
        public virtual Stuffing Stuffing { get; set; }
    }
}
